### ISSUE TITLE
Merge changes from original branch to make it work with Hugo >=v0.134+extended

### ISSUE THREAD

**Issue by khurshid-alam** [kurt-liao/github-style-plus#13]
There are lots of fixes with original version of the repo which works more recent version of Hugo. 

1. https://github.com/MeiK2333/github-style/commit/aab58c7d7b5ff55b8fd00ef24b3efe1322998322
2. https://github.com/MeiK2333/github-style/commit/046f31434c5fcc983bde13217455cc81ec5f8fef

Thanks.

**Comment by kurt-liao** [comment]
Hi @khurshid-alam , sorry for the late reply. I've been quite busy with work lately. I'll review and merge it soon. Thanks for updating me.

**Comment by kurt-liao** [comment]
@khurshid-alam I fixed the deprecated code in this [commit](https://github.com/kurt-liao/github-style-plus/commit/89dcdec92ecd3d1f5b6ac44e2df2cdfc8e510af3).
